# Generated by Django 5.1.1 on 2024-09-23 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='about_images/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('project_image', models.ImageField(upload_to='project_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('service1_title', models.CharField(max_length=100)),
                ('service1_icon', models.ImageField(upload_to='services_icons/')),
                ('service2_title', models.CharField(max_length=100)),
                ('service2_icon', models.ImageField(upload_to='services_icons/')),
                ('service3_title', models.CharField(max_length=100)),
                ('service3_icon', models.ImageField(upload_to='services_icons/')),
            ],
        ),
    ]
