# Generated by Django 5.1.1 on 2024-09-23 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='heading',
        ),
    ]
